declare const styles: {
  readonly "sectionTeam": string;
  readonly "backgroundShapes": string;
  readonly "petShape": string;
  readonly "pawPrint1": string;
  readonly "pawPrint2": string;
  readonly "pawPrint3": string;
  readonly "heartShape": string;
  readonly "stethoscopeShape": string;
  readonly "container": string;
  readonly "sectionHead": string;
  readonly "col12": string;
  readonly "title": string;
  readonly "teamIntro": string;
  readonly "introIcon": string;
  readonly "introText": string;
  readonly "introText2": string;
  readonly "expertiseHighlight": string;
  readonly "medalIcon": string;
  readonly "teamRow": string;
  readonly "teamCol": string;
  readonly "fadeInUp": string;
  readonly "teamCard": string;
  readonly "active": string;
  readonly "teamMedia": string;
  readonly "teamImage": string;
  readonly "appointmentButton": string;
  readonly "teamContent": string;
  readonly "clearfix": string;
  readonly "teamName": string;
  readonly "teamPosition": string;
  readonly "detailButton": string;
  readonly "socialLinks": string;
  readonly "teamInfo": string;
  readonly "readMoreButton": string;
};

export default styles;
